### PR TITLE
docs: add stats in README

### PR DESCRIPTION
**Pull request by EvolutionX-10**

### CODE REVIEW

**Comment by Murtatrxx** [comment]
I don’t know, I think it’s not really needed in both cli and handler repos

**Comment by EvolutionX-10** [comment]
it looks cool and gives brief info of project activity

**Comment by Murtatrxx** [comment]
Instead of doing that, can we specify the stats verbosely like, more than 300 pull requests viewed… etc

**Review by Murtatrxx — CHANGES_REQUESTED** [review]
Instead of an image, we verbosely specify the stats. We don’t need that, people won’t look readme for repository stats

**Pull request closed without merging**
