### PR TITLE
fix: queuing events (#332) @Benzo-Fury

### PR DESCRIPTION
**Pull request by Benzo-Fury**

### CODE REVIEW

**Comment by Benzo-Fury** [comment]
Ignore all the name changes 🙈

**Comment by Benzo-Fury** [comment]
Most recent commit removes the fix, possibly revert back to the first commit.

**Review by SrIzan10 — APPROVED** [review]
hi

**Comment by jacoobes** [comment]
Redirect: this will be merged into another subbranch

**Review by jacoobes — APPROVED** [review]
tested locally, no more blocking commands

**Pull request merged**
